"""empty message

Revision ID: 0858c349efdb
Revises: a0e4ec31e10a
Create Date: 2025-10-04 19:46:44.498378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0858c349efdb'
down_revision = 'a0e4ec31e10a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrition_label', sa.Column('nutrition_data2', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nutrition_label', 'nutrition_data2')
    # ### end Alembic commands ###
