"""Rename rec_Calories to rec_calories

Revision ID: a0e4ec31e10a
Revises: a0ff3d3571f9
Create Date: 2025-10-04 17:28:00.385527

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a0e4ec31e10a'
down_revision = 'a0ff3d3571f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('rec_calories', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('rec_protein', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('rec_carbs', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('rec_fats', sa.Float(), nullable=True))
    op.drop_column('user', 'rec_Calories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('rec_Calories', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('user', 'rec_fats')
    op.drop_column('user', 'rec_carbs')
    op.drop_column('user', 'rec_protein')
    op.drop_column('user', 'rec_calories')
    # ### end Alembic commands ###
